CREATE OR REPLACE PROCEDURE prcRegistrarEmpresa (P_NIT IN EMPRESA.EM_NIT%TYPE, 
P_NOMBRE IN EMPRESA.EM_NOMBRE%TYPE, P_FECHA_CREACION IN EMPRESA.EM_FECHA_CREACION%TYPE)
IS
BEGIN
    INSERT 
    INTO EMPRESA 
    VALUES(P_NIT, P_NOMBRE, P_FECHA_CREACION);
END prcRegistrarEmpresa;

CREATE OR REPLACE PROCEDURE prcRegistrarPortatil (P_NRO_SERIAL IN COMPUTADOR.COM_NRO_SERIAL%TYPE, 
    P_NIT IN EMPRESA.EM_NIT%TYPE, P_MARCA IN COMPUTADOR.COM_MARCA%TYPE, 
    P_CAP_DISCO_DURO_GB IN COMPUTADOR.COM_CAP_DISCO_DURO_GB%TYPE, 
    P_TIPO_DISCO_DURO IN COMPUTADOR.COM_TIPO_DISCO_DURO%TYPE,
    P_CAP_MEMORIA_RAM_GB IN COMPUTADOR.COM_CAP_MEMORIA_RAM_GB%TYPE,
    P_FECHA_ENSAMBLE IN COMPUTADOR.COM_FECHA_ENSAMBLE%TYPE)
IS
BEGIN
    INSERT 
    INTO COMPUTADOR
    VALUES(P_NRO_SERIAL, P_NIT, P_MARCA, P_CAP_DISCO_DURO_GB, P_TIPO_DISCO_DURO, P_CAP_MEMORIA_RAM_GB, P_FECHA_ENSAMBLE);
END prcRegistrarPortatil;



-----------------------------------------------------------------------------------------------------------------------------------
--TESTING PROCEDURE, NOT FINISHED
CREATE OR REPLACE PROCEDURE prcConsPortatilesMarca(P_NOMBRE IN EMPRESA.EM_NOMBRE%TYPE, P_MARCA IN COMPUTADOR.COM_MARCA%TYPE)
IS
    TYPE portatilesMarcaType IS RECORD
    (
        COM_NRO_SERIAL COMPUTADOR.COM_NRO_SERIAL%TYPE,
        COM_CAP_DISCO_DURO_GB COMPUTADOR.COM_CAP_DISCO_DURO_GB%TYPE,
        COM_CAP_MEMORIA_RAM_GB COMPUTADOR.COM_CAP_MEMORIA_RAM_GB%TYPE
    );
    portatilesMarcaRecord portatilesMarcaType;

BEGIN
    SELECT COM_NRO_SERIAL, COM_CAP_DISCO_DURO_GB, COM_CAP_MEMORIA_RAM_GB
    INTO portatilesMarcaRecord
    FROM EMPRESA 
    INNER JOIN COMPUTADOR ON EMPRESA.EM_NIT = COMPUTADOR.EM_NIT
    WHERE (P_NOMBRE LIKE EMPRESA.EM_NOMBRE AND P_MARCA LIKE COMPUTADOR.COM_MARCA);
END prcConsPortatilesMarca;

prcConsPortatilesMarca('The Eternal Tao', 'Asus');
-----------------------------------------------------------------------------------------------------------------------------------

